name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push Docker image
        run: |
          echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
          docker buildx create --use
          docker buildx build . \
            --file Dockerfile \
            --tag saltycatfish/salty_gmailer:$(date +%s) \
            --tag saltycatfish/salty_gmailer:latest \
            --push
